### PR TITLE
Test on Ruby 3

### PR DESCRIPTION
**Pull request by tas50**
Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by marcparadise** [comment]
@tas50 anything to flesh this out with?

**Comment by tas50** [comment]
It didn't work 🤷

**Comment by damacus** [comment]
@tas50 those failures are pending tests, buildkite is treating the 128 exit code as an error. 

That said I'm still seeing weird/useless stack traces every time an error occurs with the latest workstation.

**Comment by tas50** [comment]
Engineering is going to need to tackle this one.

**Pull request closed without merging**
